
services:
  db:
    image: postgres:15
    container_name: service-booking-system-database
    environment:
      POSTGRES_DB: ${DOCKER_DB_NAME}
      POSTGRES_USER: ${DOCKER_DB_HOST}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: service-booking-system-backend
    ports:
      - "${DOCKER_SPRING_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${DOCKER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_DB_HOST}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env

  

networks:
  app_network:
    driver: bridge
